### 1) Создание задач с большими файлами
POST http://localhost:8080/tasks
Content-Type: application/octet-stream

{ "urls": [
  "https://golang.org/doc/gopher/frontpage.png",
  "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.1.0-amd64-netinst.iso"
]}


### 2) Проверка статуса (нужно подставить на полученный id)
GET http://localhost:8080/tasks/id


# 3) Инструкция
#  - Пока статус "running" в JSONе при скачивании файла, нужно остановить приложение (Stop в GoLand или Ctrl+C).
#  - Запустить сервис снова.
#  - Выполнить повторный GET-запрос.


